# Generated by Django 5.2.7 on 2025-10-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='picture',
            field=models.ImageField(blank=True, default='picture/default.jpg', upload_to='picture'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
