# Generated by Django 5.2.7 on 2025-10-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_picture_question_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.ImageField(blank=True, upload_to='picture'),
        ),
    ]
