# Generated by Django 5.2.7 on 2025-10-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expires at'),
        ),
    ]
